version: "3"
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - ./node_modules:/app/node_modules/
    ports:
      - "4000:4000"
      - "9229:9229"
    environment:
      - PORT=4000
      - JWT_SECRET_KEY=B010B514AD927302CD6601063436B51B2ED1BFC7945DF3426796243FB356AC7F
      - DB_URL=mongodb://mongo:27017/database
      # - DEBUG=infra:*
      # - DEBUG=socket:server*
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db